data:
  project_name: "AnalogAI"
  architecture: "resnet18"
  dataset: "cifar10"
  n_classes: 10
  
training: 
  optimizer: "Adam"
  batch_size: 64
  lr: 0.001
  weight_decay: 0.0005
  momentum: 0.000000001
  epochs: 200
  warmup: 1000
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001
  grad_clip: 1.0

recovery:
  noise: 
    act_inject:
      use: True
      type: "Gaussian" # "uniform"
      mean: 1.0
      sigma: 0.1666667
      mask: None
      add: false
      mul: True
    weight_inject: 
      use: True
      type: "Gaussian" # "uniform"
      mean: 1.0
      sigma: 0.1666667
      add: false
      mul: True
      level: 0.1

  optimizer: 
    sam: True
    adaptive: false # ASAM
  adversarial: false   # "FGSM"、"PGD"
  qat: 
    use: false
    a_bits: 8
    w_bits: 8
